messages
A UDP Messaging Application (P2P)

* Introduction

'Messages' is a UDP based, Peer-to-peer (P2P) messaging application.
Communication is unencrypted and in no way is delivery guaranteed. In order for
a message to be received, a client needs to be listening. Retransmissions and
multipath transmission will cause messages to be repeated if they
are all successfully received. 

This application was written to investigate how message transmission delays (eg.
those caused by large distances) affect message based communication.

* Compilation on Ubuntu (and Debian based systems)
#+begin_src shell
  sudo apt install build-essential
  sudo apt install libgtk-3-dev
  sudo apt install  
  cd ./src
  make
#+end_src

To clean upper
#+begin_src shell
  make clean
#+end_src

* To Run
As the application uses GSettings to store some default values, these need to be
available in order for the software to run.

This can either be from the local cache file or from the system configuration if
it has been installed.

To run the software with the local settings use:
#+begin_src text
  cd ./src
  make run
#+end_src
otherwise, use
#+begin_src text
  cd ./src
  ./messages
#+end_src

* Configuration
* Development
#+begin_src shell
  sudo apt install libncurses-dev ncurses-doc
#+end_src
*** Useful Utilities
#+begin_src shell
  sudo apt install net-tools
#+end_src
* Status and Roadmap
Not yet feature complete - Work in Progress
- See: TODO.org

* Author

Paul Schulz <paul@mawsonlakes.org>
Copyright 2021-2022

Licence: GNU AFFERO GENERAL PUBLIC LICENSE
